apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
  namespace: solar-system
spec:
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      # imagePullSecrets:
      # - name: my-ecr-registry-key
      containers:
      - name: solar-system
        image: chinmayapradhan/orbit-engine:5259052a69545eda02f7aa72933801740901e74d
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http 
          protocol: TCP 
        envFrom:
        - secretRef:
            name: mongo-db-creds

