apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: solar-system
type: Opaque
data:
  MONGO_PASSWORD: U3VwZXJQYXNzd29yZA==           # SuperPassword
  MONGO_USERNAME: c3VwZXJ1c2Vy                               # superuser
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
